services:

  test:
    build: .
    container_name: rest-api-tests
    environment:
      GOREST_TOKEN: ${GOREST_TOKEN}
      FOOTBALL_DATA_TOKEN: ${FOOTBALL_DATA_TOKEN}
      TEST_ENV: ${TEST_ENV:-testing}
      REPORT_NAME: ${REPORT_NAME:-REST API Test Suite}
      BUILD_NUMBER: ${BUILD_NUMBER:-1}
      BUILD_NAME: ${BUILD_NAME:-}
      BUILD_URL: ${BUILD_URL:-}
      EXECUTOR_NAME: ${EXECUTOR_NAME:-pytest}
      EXECUTOR_TYPE: ${EXECUTOR_TYPE:-pytest}
    volumes:
      - ./allure-results:/app/allure-results
    command:  >
      pytest -v --alluredir=allure-results

  performance:
    build: .
    container_name: locust-runner
    ports:
      - "8089:8089"
    environment:
      GOREST_TOKEN: ${GOREST_TOKEN}
    command: >
      locust -f performance/locustfile.py
      --host=https://gorest.co.in/public/v2

  allure:
    image: frankescobar/allure-docker-service
    container_name: allure-service
    ports:
      - "5050:5050"
    restart: unless-stopped
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: 1
    volumes:
      - ./allure-results:/app/allure-results
      - ./allure-reports:/app/default-reports
