version: "3.9"

services:

  test:
    build: .
    container_name: rest-api-tests
    environment:
      GOREST_TOKEN: ${GOREST_TOKEN}
      FOOTBALL_DATA_TOKEN: ${FOOTBALL_DATA_TOKEN}
    volumes:
      - ./allure-results:/app/allure-results
    command: pytest --alluredir=allure-results

  performance:
    build: .
    container_name: locust-runner
    ports:
      - "8089:8089"
    environment:
      GOREST_TOKEN: ${GOREST_TOKEN}
    command: >
      locust -f performance/locustfile.py
      --host=https://gorest.co.in/public/v2

  allure:
    image: frankescobar/allure-docker-service
    container_name: allure-service
    ports:
      - "5050:5050"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 3
      KEEP_HISTORY: 1
    volumes:
      - ./allure-results:/app/allure-results
