[tool.poetry]
name = "python-rest-api-tests"
version = "0.1.0"
description = "Test automation framework for REST API in Python"
authors = ["Oleksandr Pylkevych <olek_on_github@sent.com>"]
readme = "README.md"
packages = [{ include = "api_client", from = "src" }]


[tool.poetry.dependencies]
python = ">=3.11,<3.15"
httpx = "0.28.1"

[tool.poetry.group.dev.dependencies]
pytest = "9.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--strict-markers -ra"
markers = [
    "smoke: run smoke tests"
]
