[tool.poetry]
name = "python-rest-api-tests"
version = "0.1.0"
description = "Test automation framework for REST API in Python"
authors = ["Oleksandr Pylkevych <olek_on_github@sent.com>"]
readme = "README.md"
packages = [
    { include = "rest_api_client", from = "src" }
]


[tool.poetry.dependencies]
python = ">=3.11,<3.15"
httpx = "0.28.1"
pydantic = "^2.12.5"
faker = "^40.4.0"
email-validator = "^2.3.0"
allure-pytest = "^2.15.3"

[tool.poetry.group.dev.dependencies]
pytest = "9.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--strict-markers -ra"
markers = [
    "smoke: run smoke tests",
    "destructive: modified external state",
    "negative: negative test cases",
    "end2end: end-to-end test cases"
]
